"$schema" = 'https://starship.rs/config-schema.json'

# C1=#d4a959  C2=#b87346  C3=#8c5889  C4=#5b6aad  C5=#252a3a

format = """
[░▒▓](#d4a959)\
[  ](bg:#d4a959 fg:#090c0c)\
[](bg:#b87346 fg:#d4a959)\
$directory\
[](fg:#b87346 bg:#8c5889)\
$git_branch\
$git_status\
[](fg:#8c5889 bg:#5b6aad)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#5b6aad bg:#252a3a)\
$time\
[](fg:#252a3a)\
\n$character"""

[directory]
style = "fg:#ffffff bg:#b87346"
format = "[ $path ]($style)"
truncation_length = 100
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#8c5889"
format = '[[ $symbol $branch ](fg:#ffffff bg:#8c5889)]($style)'

[git_status]
style = "bg:#8c5889"
format = '[[($all_status$ahead_behind )](fg:#ffffff bg:#8c5889)]($style)'

[nodejs]
symbol = ""
style = "bg:#5b6aad"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#5b6aad)]($style)'

[rust]
symbol = ""
style = "bg:#5b6aad"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#5b6aad)]($style)'

[golang]
symbol = ""
style = "bg:#5b6aad"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#5b6aad)]($style)'

[php]
symbol = ""
style = "bg:#5b6aad"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#5b6aad)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#252a3a"
format = '[[   $time](fg:#a0a8c8 bg:#252a3a)]($style)'

[character]
disabled = false
success_symbol = '[❯](bold fg:#b87346)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold fg:#b87346)'
