"$schema" = 'https://starship.rs/config-schema.json'

# C1=#e89d45  C2=#4a90d9  C3=#a07ed1  C4=#26a69a  C5=#2d3149

format = """
[░▒▓](#e89d45)\
[  ](bg:#e89d45 fg:#090c0c)\
[](bg:#4a90d9 fg:#e89d45)\
$directory\
[](fg:#4a90d9 bg:#a07ed1)\
$git_branch\
$git_status\
[](fg:#a07ed1 bg:#26a69a)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#26a69a bg:#2d3149)\
$time\
[](fg:#2d3149)\
\n$character"""

[directory]
style = "fg:#ffffff bg:#4a90d9"
format = "[ $path ]($style)"
truncation_length = 100
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#a07ed1"
format = '[[ $symbol $branch ](fg:#ffffff bg:#a07ed1)]($style)'

[git_status]
style = "bg:#a07ed1"
format = '[[($all_status$ahead_behind )](fg:#ffffff bg:#a07ed1)]($style)'

[nodejs]
symbol = ""
style = "bg:#26a69a"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#26a69a)]($style)'

[rust]
symbol = ""
style = "bg:#26a69a"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#26a69a)]($style)'

[golang]
symbol = ""
style = "bg:#26a69a"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#26a69a)]($style)'

[php]
symbol = ""
style = "bg:#26a69a"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#26a69a)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#2d3149"
format = '[[   $time](fg:#c8d3f5 bg:#2d3149)]($style)'

[character]
disabled = false
success_symbol = '[❯](bold fg:#4a90d9)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold fg:#4a90d9)'
