"$schema" = 'https://starship.rs/config-schema.json'

# C1=#5e81ac  C2=#81a1c1  C3=#8fbcbb  C4=#88c0d0  C5=#434c5e

format = """
[░▒▓](#5e81ac)\
[  ](bg:#5e81ac fg:#090c0c)\
[](bg:#81a1c1 fg:#5e81ac)\
$directory\
[](fg:#81a1c1 bg:#8fbcbb)\
$git_branch\
$git_status\
[](fg:#8fbcbb bg:#88c0d0)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#88c0d0 bg:#434c5e)\
$time\
[](fg:#434c5e)\
\n$character"""

[directory]
style = "fg:#ffffff bg:#81a1c1"
format = "[ $path ]($style)"
truncation_length = 100
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#8fbcbb"
format = '[[ $symbol $branch ](fg:#ffffff bg:#8fbcbb)]($style)'

[git_status]
style = "bg:#8fbcbb"
format = '[[($all_status$ahead_behind )](fg:#ffffff bg:#8fbcbb)]($style)'

[nodejs]
symbol = ""
style = "bg:#88c0d0"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#88c0d0)]($style)'

[rust]
symbol = ""
style = "bg:#88c0d0"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#88c0d0)]($style)'

[golang]
symbol = ""
style = "bg:#88c0d0"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#88c0d0)]($style)'

[php]
symbol = ""
style = "bg:#88c0d0"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#88c0d0)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#434c5e"
format = '[[   $time](fg:#d8dee9 bg:#434c5e)]($style)'

[character]
disabled = false
success_symbol = '[❯](bold fg:#81a1c1)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold fg:#81a1c1)'
