"$schema" = 'https://starship.rs/config-schema.json'

# C1=#f0a0a0  C2=#a8d8ea  C3=#f7d794  C4=#b8e6c8  C5=#3d4555

format = """
[░▒▓](#f0a0a0)\
[  ](bg:#f0a0a0 fg:#090c0c)\
[](bg:#a8d8ea fg:#f0a0a0)\
$directory\
[](fg:#a8d8ea bg:#f7d794)\
$git_branch\
$git_status\
[](fg:#f7d794 bg:#b8e6c8)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#b8e6c8 bg:#3d4555)\
$time\
[](fg:#3d4555)\
\n$character"""

[directory]
style = "fg:#2b2d3a bg:#a8d8ea"
format = "[ $path ]($style)"
truncation_length = 100
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#f7d794"
format = '[[ $symbol $branch ](fg:#2b2d3a bg:#f7d794)]($style)'

[git_status]
style = "bg:#f7d794"
format = '[[($all_status$ahead_behind )](fg:#2b2d3a bg:#f7d794)]($style)'

[nodejs]
symbol = ""
style = "bg:#b8e6c8"
format = '[[ $symbol ($version) ](fg:#2b2d3a bg:#b8e6c8)]($style)'

[rust]
symbol = ""
style = "bg:#b8e6c8"
format = '[[ $symbol ($version) ](fg:#2b2d3a bg:#b8e6c8)]($style)'

[golang]
symbol = ""
style = "bg:#b8e6c8"
format = '[[ $symbol ($version) ](fg:#2b2d3a bg:#b8e6c8)]($style)'

[php]
symbol = ""
style = "bg:#b8e6c8"
format = '[[ $symbol ($version) ](fg:#2b2d3a bg:#b8e6c8)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#3d4555"
format = '[[   $time](fg:#c8cfe0 bg:#3d4555)]($style)'

[character]
disabled = false
success_symbol = '[❯](bold fg:#a8d8ea)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold fg:#a8d8ea)'
