"$schema" = 'https://starship.rs/config-schema.json'

# C1=#d08770  C2=#88c0d0  C3=#ebcb8b  C4=#8fbcbb  C5=#434c5e

format = """
[░▒▓](#d08770)\
[  ](bg:#d08770 fg:#090c0c)\
[](bg:#88c0d0 fg:#d08770)\
$directory\
[](fg:#88c0d0 bg:#ebcb8b)\
$git_branch\
$git_status\
[](fg:#ebcb8b bg:#8fbcbb)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#8fbcbb bg:#434c5e)\
$time\
[](fg:#434c5e)\
\n$character"""

[directory]
style = "fg:#ffffff bg:#88c0d0"
format = "[ $path ]($style)"
truncation_length = 100
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#ebcb8b"
format = '[[ $symbol $branch ](fg:#ffffff bg:#ebcb8b)]($style)'

[git_status]
style = "bg:#ebcb8b"
format = '[[($all_status$ahead_behind )](fg:#ffffff bg:#ebcb8b)]($style)'

[nodejs]
symbol = ""
style = "bg:#8fbcbb"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#8fbcbb)]($style)'

[rust]
symbol = ""
style = "bg:#8fbcbb"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#8fbcbb)]($style)'

[golang]
symbol = ""
style = "bg:#8fbcbb"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#8fbcbb)]($style)'

[php]
symbol = ""
style = "bg:#8fbcbb"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#8fbcbb)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#434c5e"
format = '[[   $time](fg:#d8dee9 bg:#434c5e)]($style)'

[character]
disabled = false
success_symbol = '[❯](bold fg:#88c0d0)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold fg:#88c0d0)'
