"$schema" = 'https://starship.rs/config-schema.json'

# C1=#b090e8  C2=#8b6cc8  C3=#7a60b8  C4=#9880d0  C5=#272340

format = """
[░▒▓](#b090e8)\
[  ](bg:#b090e8 fg:#090c0c)\
[](bg:#8b6cc8 fg:#b090e8)\
$directory\
[](fg:#8b6cc8 bg:#7a60b8)\
$git_branch\
$git_status\
[](fg:#7a60b8 bg:#9880d0)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#9880d0 bg:#272340)\
$time\
[](fg:#272340)\
\n$character"""

[directory]
style = "fg:#ffffff bg:#8b6cc8"
format = "[ $path ]($style)"
truncation_length = 100
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#7a60b8"
format = '[[ $symbol $branch ](fg:#ffffff bg:#7a60b8)]($style)'

[git_status]
style = "bg:#7a60b8"
format = '[[($all_status$ahead_behind )](fg:#ffffff bg:#7a60b8)]($style)'

[nodejs]
symbol = ""
style = "bg:#9880d0"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#9880d0)]($style)'

[rust]
symbol = ""
style = "bg:#9880d0"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#9880d0)]($style)'

[golang]
symbol = ""
style = "bg:#9880d0"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#9880d0)]($style)'

[php]
symbol = ""
style = "bg:#9880d0"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#9880d0)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#272340"
format = '[[   $time](fg:#c8b8f0 bg:#272340)]($style)'

[character]
disabled = false
success_symbol = '[❯](bold fg:#8b6cc8)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold fg:#8b6cc8)'
