"$schema" = 'https://starship.rs/config-schema.json'

# C1=#c9796b  C2=#d4a27f  C3=#a3b18a  C4=#8a7e6b  C5=#3e3832

format = """
[░▒▓](#c9796b)\
[  ](bg:#c9796b fg:#090c0c)\
[](bg:#d4a27f fg:#c9796b)\
$directory\
[](fg:#d4a27f bg:#a3b18a)\
$git_branch\
$git_status\
[](fg:#a3b18a bg:#8a7e6b)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#8a7e6b bg:#3e3832)\
$time\
[](fg:#3e3832)\
\n$character"""

[directory]
style = "fg:#2b2420 bg:#d4a27f"
format = "[ $path ]($style)"
truncation_length = 100
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#a3b18a"
format = '[[ $symbol $branch ](fg:#2b2420 bg:#a3b18a)]($style)'

[git_status]
style = "bg:#a3b18a"
format = '[[($all_status$ahead_behind )](fg:#2b2420 bg:#a3b18a)]($style)'

[nodejs]
symbol = ""
style = "bg:#8a7e6b"
format = '[[ $symbol ($version) ](fg:#2b2420 bg:#8a7e6b)]($style)'

[rust]
symbol = ""
style = "bg:#8a7e6b"
format = '[[ $symbol ($version) ](fg:#2b2420 bg:#8a7e6b)]($style)'

[golang]
symbol = ""
style = "bg:#8a7e6b"
format = '[[ $symbol ($version) ](fg:#2b2420 bg:#8a7e6b)]($style)'

[php]
symbol = ""
style = "bg:#8a7e6b"
format = '[[ $symbol ($version) ](fg:#2b2420 bg:#8a7e6b)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#3e3832"
format = '[[   $time](fg:#c4b8a8 bg:#3e3832)]($style)'

[character]
disabled = false
success_symbol = '[❯](bold fg:#d4a27f)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold fg:#d4a27f)'
