"$schema" = 'https://starship.rs/config-schema.json'

# C1=#7a9a7e  C2=#a7c080  C3=#83c092  C4=#78b0a0  C5=#343f44

format = """
[░▒▓](#7a9a7e)\
[  ](bg:#7a9a7e fg:#090c0c)\
[](bg:#a7c080 fg:#7a9a7e)\
$directory\
[](fg:#a7c080 bg:#83c092)\
$git_branch\
$git_status\
[](fg:#83c092 bg:#78b0a0)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#78b0a0 bg:#343f44)\
$time\
[](fg:#343f44)\
\n$character"""

[directory]
style = "fg:#d5c9ab bg:#a7c080"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#83c092"
format = '[[ $symbol $branch ](fg:#a7c080 bg:#83c092)]($style)'

[git_status]
style = "bg:#83c092"
format = '[[($all_status$ahead_behind )](fg:#a7c080 bg:#83c092)]($style)'

[nodejs]
symbol = ""
style = "bg:#78b0a0"
format = '[[ $symbol ($version) ](fg:#a7c080 bg:#78b0a0)]($style)'

[rust]
symbol = ""
style = "bg:#78b0a0"
format = '[[ $symbol ($version) ](fg:#a7c080 bg:#78b0a0)]($style)'

[golang]
symbol = ""
style = "bg:#78b0a0"
format = '[[ $symbol ($version) ](fg:#a7c080 bg:#78b0a0)]($style)'

[php]
symbol = ""
style = "bg:#78b0a0"
format = '[[ $symbol ($version) ](fg:#a7c080 bg:#78b0a0)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#343f44"
format = '[[   $time ](fg:#c5b89a bg:#343f44)]($style)'

[character]
disabled = false
success_symbol = '[❯](bold fg:#a7c080)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold fg:#a7c080)'
