"$schema" = 'https://starship.rs/config-schema.json'

# C1=#f7768e  C2=#2a2d3e  C3=#1a1a2e  C4=#353b52  C5=#16161e

format = """
[░▒▓](#f7768e)\
[  ](bg:#f7768e fg:#090c0c)\
[](bg:#2a2d3e fg:#f7768e)\
$directory\
[](fg:#2a2d3e bg:#1a1a2e)\
$git_branch\
$git_status\
[](fg:#1a1a2e bg:#353b52)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#353b52 bg:#16161e)\
$time\
[](fg:#16161e)\
\n$character"""

[directory]
style = "fg:#ffffff bg:#2a2d3e"
format = "[ $path ]($style)"
truncation_length = 100
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#1a1a2e"
format = '[[ $symbol $branch ](fg:#ffffff bg:#1a1a2e)]($style)'

[git_status]
style = "bg:#1a1a2e"
format = '[[($all_status$ahead_behind )](fg:#ffffff bg:#1a1a2e)]($style)'

[nodejs]
symbol = ""
style = "bg:#353b52"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#353b52)]($style)'

[rust]
symbol = ""
style = "bg:#353b52"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#353b52)]($style)'

[golang]
symbol = ""
style = "bg:#353b52"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#353b52)]($style)'

[php]
symbol = ""
style = "bg:#353b52"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#353b52)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#16161e"
format = '[[   $time](fg:#565f89 bg:#16161e)]($style)'

[character]
disabled = false
success_symbol = '[❯](bold fg:#f7768e)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold fg:#f7768e)'
