"$schema" = 'https://starship.rs/config-schema.json'

# C1=#56b6c2  C2=#3a8578  C3=#5c6d8a  C4=#7c6f9b  C5=#1e2133

format = """
[░▒▓](#56b6c2)\
[  ](bg:#56b6c2 fg:#090c0c)\
[](bg:#3a8578 fg:#56b6c2)\
$directory\
[](fg:#3a8578 bg:#5c6d8a)\
$git_branch\
$git_status\
[](fg:#5c6d8a bg:#7c6f9b)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#7c6f9b bg:#1e2133)\
$time\
[](fg:#1e2133)\
\n$character"""

[directory]
style = "fg:#ffffff bg:#3a8578"
format = "[ $path ]($style)"
truncation_length = 100
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#5c6d8a"
format = '[[ $symbol $branch ](fg:#ffffff bg:#5c6d8a)]($style)'

[git_status]
style = "bg:#5c6d8a"
format = '[[($all_status$ahead_behind )](fg:#ffffff bg:#5c6d8a)]($style)'

[nodejs]
symbol = ""
style = "bg:#7c6f9b"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#7c6f9b)]($style)'

[rust]
symbol = ""
style = "bg:#7c6f9b"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#7c6f9b)]($style)'

[golang]
symbol = ""
style = "bg:#7c6f9b"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#7c6f9b)]($style)'

[php]
symbol = ""
style = "bg:#7c6f9b"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#7c6f9b)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#1e2133"
format = '[[   $time](fg:#8890a8 bg:#1e2133)]($style)'

[character]
disabled = false
success_symbol = '[❯](bold fg:#3a8578)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold fg:#3a8578)'
