"$schema" = 'https://starship.rs/config-schema.json'

# C1=#4a52a0  C2=#5c65b8  C3=#3a4270  C4=#354560  C5=#283040

format = """
[░▒▓](#4a52a0)\
[  ](bg:#4a52a0 fg:#090c0c)\
[](bg:#5c65b8 fg:#4a52a0)\
$directory\
[](fg:#5c65b8 bg:#3a4270)\
$git_branch\
$git_status\
[](fg:#3a4270 bg:#354560)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#354560 bg:#283040)\
$time\
[](fg:#283040)\
\n$character"""

[directory]
style = "fg:#ffffff bg:#5c65b8"
format = "[ $path ]($style)"
truncation_length = 100
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#3a4270"
format = '[[ $symbol $branch ](fg:#ffffff bg:#3a4270)]($style)'

[git_status]
style = "bg:#3a4270"
format = '[[($all_status$ahead_behind )](fg:#ffffff bg:#3a4270)]($style)'

[nodejs]
symbol = ""
style = "bg:#354560"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#354560)]($style)'

[rust]
symbol = ""
style = "bg:#354560"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#354560)]($style)'

[golang]
symbol = ""
style = "bg:#354560"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#354560)]($style)'

[php]
symbol = ""
style = "bg:#354560"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#354560)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#283040"
format = '[[   $time](fg:#a8b8d8 bg:#283040)]($style)'

[character]
disabled = false
success_symbol = '[❯](bold fg:#5c65b8)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold fg:#5c65b8)'
