"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$python\
$docker_context\
$line_break$character"""

[username]
show_always = true
style_user = "bold #7aa2f7"
style_root = "bold #f7768e"
format = '[$user]($style) '

[hostname]
ssh_only = true
style = "bold #9ece6a"
format = 'on [$hostname]($style) '

[directory]
style = "bold #e0af68"
format = '[$path]($style) '
truncation_length = 5
truncation_symbol = "â€¦/"
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bold #a9b1d6"
format = '[$symbol$branch]($style) '

[git_status]
style = "bold #f7768e"
format = '[$all_status$ahead_behind]($style) '

[nodejs]
symbol = " "
style = "#9ece6a"
format = '[$symbol$version]($style) '

[c]
symbol = " "
style = "#9ece6a"
format = '[$symbol$version]($style) '

[rust]
symbol = " "
style = "#9ece6a"
format = '[$symbol$version]($style) '

[golang]
symbol = " "
style = "#9ece6a"
format = '[$symbol$version]($style) '

[php]
symbol = " "
style = "#9ece6a"
format = '[$symbol$version]($style) '

[java]
symbol = " "
style = "#9ece6a"
format = '[$symbol$version]($style) '

[kotlin]
symbol = " "
style = "#9ece6a"
format = '[$symbol$version]($style) '

[python]
symbol = " "
style = "#9ece6a"
format = '[$symbol$version]($style) '

[docker_context]
symbol = " "
style = "#7dcfff"
format = '[$symbol$context]($style) '

[time]
disabled = true

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[>](bold #9ece6a)'
error_symbol = '[>](bold #f7768e)'
vimcmd_symbol = '[<](bold #9ece6a)'
